Node:
  MainNode:
    ip: 127.0.0.1
    port: 8334
  N1:
    ip: 127.0.0.1
    port: 8334
bind:
  id: N0
  ip: 127.0.0.1
  port: 8334

dataconfig:
  database: blockchain
  host: localhost
  password: '123456'
  port: 3306
  user: root
